#!/bin/sh

name="mxe"

while [ "$#" -gt 0 ]; do
	case "$1" in
		-n) name="$2"; shift 2;;
		--name=*) name="${1#*=}"; shift 1;;
		
		--name) echo "$1 requires an argument" >&2; exit 1;;

		-*) echo "unknown option: $1" >&2; exit 1;;
		*) extra="$extra $1"; shift 1;;
	esac
done

docker run --rm -v `pwd`:/workdir -w /workdir -ti -u `id -u` --name=$name -h $name $name bash

