#!/bin/sh

if [ $# -eq 0 ]; then
	echo "Docker for MXE v0.1"
	echo "Type '$0 help' for help." >&2
	exit 1;
fi

case "$1" in
	help)
		echo "Docker for MXE v0.1"
		echo ""
		if [ $# -eq 1 ]; then
			echo "$0 help            Prints this help message"
			echo "$0 help <cmd>      Prints help about a command"
			echo "$0 prepare         Creates a MXE image with a list of packages"
			echo "$0 run             Launches the image opening a shell with access to the current directory"
			echo ""
		else
			case "$2" in
				prepare)
					echo "TODO"
					;;
				run)
					echo "TODO"
					;;
			esac
		fi
		;;
	
	prepare) shift 1;
		name="default"
		mxedir=""
		
		while [ "$#" -gt 0 ]; do
			case "$1" in
				-n) name="$2"; shift 2;;
				--name=*) name="${1#*=}"; shift 1;;
				
				--name|--mxedir) echo "$1 requires an argument" >&2; exit 1;;
		
				*) echo "unknown option: $1" >&2; exit 1;;
			esac
		done
		
		mxedir="/opt/mxe/$name"
		
		(
		echo "FROM debian:stable"
		echo "RUN apt-get update && apt-get upgrade -y"
		echo "RUN apt-get install -y --no-install-recommends git ca-certificates make wget autoconf automake autopoint cmake bison flex bzip2 g++ gperf intltool libtool libtool-bin python ruby scons unzip p7zip-full pkg-config libffi-dev"
		echo "WORKDIR /mxe"
		echo "ENV PATH=/mxe/usr/bin:\$PATH"
		echo "RUN useradd -d /workdir -u $(id -u) mxe"
		) | docker build -t mxe -
		
		if [ -f "$mxedir/Makefile" ]
		then
			echo "Skip cloning git, MXE already exists at $mxedir"
		else
			docker run --rm -v $mxedir:/mxe -w / --name=mxe-$name mxe git clone https://github.com/mxe/mxe
		fi
		
		;;
	
	make) shift 1;
		name="default"
		
		while [ "$#" -gt 0 ]; do
			case "$1" in
				-n) name="$2"; shift 2;;
				--name=*) name="${1#*=}"; shift 1;;
				
				--name) echo "$1 requires an argument" >&2; exit 1;;
		
				-*) echo "unknown option: $1" >&2; exit 1;;
				*) extra="$extra $1"; shift 1;;
			esac
		done
		
		mxedir="/opt/mxe/$name"
		
		echo "Running make at $mxedir"
		
		docker run --rm -v $mxedir:/mxe -w /mxe --name=mxe-$name mxe make $extra
		;;
	
	run) shift 1;
		name="default"
		
		while [ "$#" -gt 0 ]; do
			case "$1" in
				-n) name="$2"; shift 2;;
				--name=*) name="${1#*=}"; shift 1;;
				
				--name) echo "$1 requires an argument" >&2; exit 1;;
		
				*) echo "unknown option: $1" >&2; exit 1;;
			esac
		done
		
		mxedir="/opt/mxe/$name"
		
		docker run --rm -v $mxedir:/mxe -v `pwd`:/workdir -w /workdir -ti -u `id -u` --name=mxe-$name -h $name -e HISTFILE=/dev/null mxe bash
		;;
	
	*) echo "Unknown: $1" >&2; exit 1;;
esac
